
services:
    twig.extension.locale:
        class: WellCommerce\Bundle\LocaleBundle\Twig\Extension\LocaleExtension
        tags:
            - { name: twig.extension }
        arguments: ['@locale.dataset.front']

    locale.controller.front:
        class: WellCommerce\Bundle\LocaleBundle\Controller\Front\LocaleController
        arguments: ['@locale.manager']
        calls:
            - [setContainer, ['@service_container']]

    locale.subscriber:
        class: WellCommerce\Bundle\LocaleBundle\EventListener\LocaleSubscriber
        tags:
            - { name: kernel.event_subscriber }
        calls:
            - [setContainer, ['@service_container']]

    form.translation.data_transformer:
        class: WellCommerce\Bundle\LocaleBundle\Form\DataTransformer\TranslationTransformer
        tags:
            - { name: form.data_transformer, alias: translation }
        arguments: ['@doctrine.helper']
        shared: false
